modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "sacrifice"
version = "${version}"
displayName = "Sacrifice"
authors = "Kall"
description = '''
'''
#logoFile = ""

[[dependencies.sacrifice]]
modId="duplicationless"
mandatory=true
versionRange="[1.0.5,)"
ordering="NONE"
side="BOTH"